import { Minus, Plus, Trash2 } from 'lucide-react';
import { useDispatch, useSelector } from 'react-redux';
import { Link } from 'react-router-dom';
import { toast } from 'react-hot-toast';
import { clearCart, clearRemoteCart, removeItem, removeRemoteItem, selectCartTotal, updateQuantity, updateRemoteQuantity } from '../redux/slices/cartSlice';

export default function CartPage() {
  const dispatch = useDispatch(); const { items, totals } = useSelector((state) => state.cart); const user = useSelector((state) => state.auth.user); const subtotal = useSelector(selectCartTotal); const deliveryCharge = totals?.deliveryCharge ?? (subtotal === 0 || subtotal >= 500 ? 0 : 40); const gst = totals?.gst ?? Number((subtotal * 0.05).toFixed(2)); const grandTotal = totals?.grandTotal ?? subtotal + deliveryCharge + gst;
  const update = async (item, quantity) => { if (quantity < 1) return; if (!user) return dispatch(updateQuantity({ id: item._id, quantity })); try { await dispatch(updateRemoteQuantity({ productId: item._id, quantity })).unwrap(); } catch (error) { toast.error(error); } };
  const remove = async (item) => { if (!user) { dispatch(removeItem(item._id)); return toast.success('Removed from cart'); } try { await dispatch(removeRemoteItem(item._id)).unwrap(); toast.success('Removed from cart'); } catch (error) { toast.error(error); } };
  const clear = async () => { if (!user) return dispatch(clearCart()); try { await dispatch(clearRemoteCart()).unwrap(); toast.success('Cart cleared'); } catch (error) { toast.error(error); } };
  if (!items.length) return <section className="py-20 text-center"><h1 className="text-3xl font-bold">Your basket is empty</h1><p className="mt-2 text-stone-500">Add some fresh essentials to get started.</p><Link to="/" className="mt-6 inline-block rounded-xl bg-brand-600 px-5 py-3 font-bold text-white">Browse groceries</Link></section>;
  return <section className="mx-auto max-w-3xl"><div className="flex items-center justify-between"><h1 className="text-3xl font-bold">Your basket</h1><button onClick={clear} className="text-sm font-semibold text-red-600">Clear cart</button></div><div className="mt-6 space-y-3">{items.map((item) => { const image = item.images?.[0]?.url || item.image; const name = item.title || item.name; const price = item.discountPrice ?? item.price; return <article key={item._id} className="flex items-center gap-3 rounded-2xl bg-white p-3 shadow-sm ring-1 ring-stone-200"><img src={image} alt="" className="h-16 w-16 rounded-xl object-cover" /><div className="min-w-0 flex-1"><h2 className="truncate font-bold">{name}</h2><p className="text-sm text-stone-500">₹{price} / {item.unit}</p></div><div className="flex items-center gap-2"><button disabled={item.quantity <= 1} onClick={() => update(item, item.quantity - 1)} className="rounded p-1 hover:bg-stone-100 disabled:opacity-40" aria-label="Decrease quantity"><Minus size={16} /></button><span className="w-5 text-center font-bold">{item.quantity}</span><button disabled={item.quantity >= item.stock} onClick={() => update(item, item.quantity + 1)} className="rounded p-1 hover:bg-stone-100 disabled:opacity-40" aria-label="Increase quantity"><Plus size={16} /></button></div><button onClick={() => remove(item)} className="p-2 text-red-600" aria-label={`Remove ${name}`}><Trash2 size={18} /></button></article>; })}</div><div className="mt-6 rounded-2xl bg-stone-900 p-5 text-white"><div className="space-y-1 text-sm text-stone-300"><div className="flex justify-between"><span>Subtotal</span><span>₹{subtotal.toFixed(2)}</span></div><div className="flex justify-between"><span>Delivery</span><span>{deliveryCharge ? `₹${deliveryCharge.toFixed(2)}` : 'Free'}</span></div><div className="flex justify-between"><span>GST (5%)</span><span>₹{gst.toFixed(2)}</span></div></div><div className="mt-3 flex items-center justify-between border-t border-stone-700 pt-3"><p className="text-lg font-bold">Grand total</p><p className="text-2xl font-bold">₹{grandTotal.toFixed(2)}</p></div><Link to="/checkout" className="mt-5 block rounded-xl bg-brand-500 px-5 py-3 text-center font-bold">Checkout</Link></div></section>;
}
