import Category from '../models/Category.js';
 import Order from '../models/Order.js';
  import Product from '../models/Product.js'; 
  import User from '../models/User.js';
const threshold = () => Math.max(Number(process.env.LOW_STOCK_THRESHOLD) || 10, 0);
const dateRange = (days) => ({ $gte: new Date(Date.now() - days * 24 * 60 * 60 * 1000) });
export const dashboard = async (_req, res) => { 
  const [users, products, categories, orders, revenue, pendingOrders, deliveredOrders, lowStockProducts] = await Promise.all([User.countDocuments(), Product.countDocuments(), Category.countDocuments(), Order.countDocuments(), Order.aggregate([{ $match: { orderStatus: 'Delivered' } }, { $group: { _id: null, total: { $sum: '$totalAmount' } } }]), Order.countDocuments({ orderStatus: 'Pending' }), Order.countDocuments({ orderStatus: 'Delivered' }), Product.countDocuments({ stock: { $lt: threshold() } })]); return res.json({ success: true, data: { users, products, categories, orders, totalRevenue: revenue[0]?.total || 0, pendingOrders, deliveredOrders, lowStockProducts, lowStockThreshold: threshold() } }); };
export const analytics = async (_req, res) => {
  const [dailyOrders, weeklyOrders, monthlyRevenue, topProducts, topCategories] = await Promise.all([
    Order.aggregate([{ $match: { createdAt: dateRange(7) } }, { $group: { _id: { $dateToString: { format: '%Y-%m-%d', date: '$createdAt' } }, count: { $sum: 1 },}, }, { $sort: { _id: 1 } }]),
    Order.aggregate([{ $match: { createdAt: dateRange(56) } }, { $group: { _id: { $dateToString: { format: '%Y-%U', date: '$createdAt' } }, count: { $sum: 1 },}, }, { $sort: { _id: 1 } }]),
    Order.aggregate([{ $match: { orderStatus: 'Delivered', createdAt: dateRange(365) } }, { $group: { _id: { $dateToString: { format: '%Y-%m', date: '$createdAt' } }, revenue: { $sum: '$totalAmount' },}, }, { $sort: { _id: 1 } }]),
    Order.aggregate([{ $match: { orderStatus: { $ne: 'Cancelled' } } }, { $unwind: '$items' }, { $group: { _id: '$items.product', title: { $first: '$items.title' }, quantity: { $sum: '$items.quantity' }, revenue: { $sum: { $multiply: ['$items.price', '$items.quantity'] } } } }, { $sort: { quantity: -1 } }, { $limit: 5 }]),
    Order.aggregate([{ $match: { orderStatus: { $ne: 'Cancelled' } } }, { $unwind: '$items' }, { $lookup: { from: 'products', localField: 'items.product', foreignField: '_id', as: 'product' } }, { $unwind: { path: '$product', preserveNullAndEmptyArrays: true } }, { $lookup: { from: 'categories', localField: 'product.category', foreignField: '_id', as: 'category' } }, { $unwind: { path: '$category', preserveNullAndEmptyArrays: true } }, { $group: { _id: '$category.name', quantity: { $sum: '$items.quantity' } } }, { $sort: { quantity: -1 } }, { $limit: 5 }]),
  ]); return res.json({ success: true, data: { dailyOrders, weeklyOrders, monthlyRevenue, topProducts, topCategories } });
};
export const getInventory = async (req, res) => { const filter = {}; if (req.query.search) filter.title = { $regex: req.query.search, $options: 'i' }; if (req.query.lowStock === 'true') filter.stock = { $lt: threshold() }; if (req.query.available !== undefined) filter.isAvailable = req.query.available === 'true'; return res.json({ success: true, data: await Product.find(filter).populate('category', 'name').sort({ stock: 1, title: 1 }).lean(), threshold: threshold() }); };
export const adjustStock = async (req, res) => { const product = await Product.findByIdAndUpdate(req.params.id, { $inc: { stock: req.body.change } }, { new: true, runValidators: true }); if (!product || product.stock < 0) { if (product?.stock < 0) await Product.updateOne({ _id: product._id }, { $inc: { stock: -req.body.change } }); return res.status(422).json({ success: false, message: 'Stock cannot be negative' }); } return res.json({ success: true, data: product }); };
export const bulkStock = async (req, res) => { const invalid = req.body.items.find((item) => item.stock < 0); if (invalid) return res.status(422).json({ success: false, message: 'Stock cannot be negative' }); await Product.bulkWrite(req.body.items.map((item) => ({ updateOne: { filter: { _id: item.productId }, update: { $set: { stock: item.stock } } } }))); return res.json({ success: true, message: 'Inventory updated' }); };
export const setAvailability = async (req, res) => { const product = await Product.findByIdAndUpdate(req.params.id, { isAvailable: req.body.isAvailable }, { new: true }); if (!product) return res.status(404).json({ success: false, message: 'Product not found' }); return res.json({ success: true, data: product }); };
export const getUsers = async (req, res) => { const filter = req.query.search ? { $or: [{ name: { $regex: req.query.search, $options: 'i' } }, { email: { $regex: req.query.search, $options: 'i' } }] } : {}; return res.json({ success: true, data: await User.find(filter).select('name email phone role createdAt').sort({ createdAt: -1 }).limit(100).lean() }); };
