import { Readable } from 'stream';
import cloudinary, { cloudinaryConfigured } from '../config/cloudinary.js';
import Banner from '../models/Banner.js';

const uploadImage = (file) => new Promise((resolve, reject) => { const stream = cloudinary.uploader.upload_stream({ folder: 'freshbasket/banners', resource_type: 'image' }, (error, result) => error ? reject(error) : resolve({ url: result.secure_url, publicId: result.public_id })); Readable.from(file.buffer).pipe(stream); });
const values = (body) => ({ ...body, isActive: body.isActive === 'true' || body.isActive === true, sortOrder: Number(body.sortOrder || 0) });
export const getBanners = async (req, res) => { const filter = req.user?.role === 'admin' && req.query.includeInactive === 'true' ? {} : { isActive: true }; return res.json({ success: true, data: await Banner.find(filter).sort({ sortOrder: 1, createdAt: -1 }).lean() }); };
export const createBanner = async (req, res) => { if (!req.file) return res.status(422).json({ success: false, message: 'Select a banner image' }); if (!cloudinaryConfigured()) return res.status(503).json({ success: false, message: 'Cloudinary is not configured' }); return res.status(201).json({ success: true, data: await Banner.create({ ...values(req.body), image: await uploadImage(req.file) }) }); };
export const updateBanner = async (req, res) => { const banner = await Banner.findById(req.params.id); if (!banner) return res.status(404).json({ success: false, message: 'Banner not found' }); if (req.file) { if (!cloudinaryConfigured()) return res.status(503).json({ success: false, message: 'Cloudinary is not configured' }); const image = await uploadImage(req.file); if (banner.image.publicId) await cloudinary.uploader.destroy(banner.image.publicId); banner.image = image; } Object.assign(banner, values(req.body)); await banner.save(); return res.json({ success: true, data: banner }); };
export const deleteBanner = async (req, res) => { const banner = await Banner.findByIdAndDelete(req.params.id); if (!banner) return res.status(404).json({ success: false, message: 'Banner not found' }); if (banner.image.publicId && cloudinaryConfigured()) await cloudinary.uploader.destroy(banner.image.publicId); return res.json({ success: true, message: 'Banner deleted' }); };
export const reorderBanners = async (req, res) => { await Promise.all(req.body.items.map(({ id, sortOrder }) => Banner.updateOne({ _id: id }, { sortOrder }))); return res.json({ success: true, data: await Banner.find().sort({ sortOrder: 1 }).lean() }); };
