import mongoose from 'mongoose';
import Category from '../models/Category.js';
import Product from '../models/Product.js';

const pageDetails = (query) => ({ page: Math.max(Number(query.page) || 1, 1), limit: Math.min(Math.max(Number(query.limit) || 20, 1), 100) });
export const getCategories = async (req, res) => { const { page, limit } = pageDetails(req.query); const showInactive = req.query.includeInactive === 'true' && req.user?.role === 'admin'; const filter = showInactive ? {} : { isActive: true }; const [categories, total] = await Promise.all([Category.find(filter).sort({ name: 1 }).skip((page - 1) * limit).limit(limit).lean(), Category.countDocuments(filter)]); return res.status(200).json({ success: true, data: categories, pagination: { page, limit, total, pages: Math.ceil(total / limit) } }); };
export const getCategory = async (req, res) => { const selector = mongoose.isObjectIdOrHexString(req.params.id) ? { $or: [{ _id: req.params.id }, { slug: req.params.id }] } : { slug: req.params.id }; const category = await Category.findOne(selector).lean(); if (!category) return res.status(404).json({ success: false, message: 'Category not found' }); return res.status(200).json({ success: true, data: category }); };
export const createCategory = async (req, res) => { const category = await Category.create(req.body); return res.status(201).json({ success: true, data: category }); };
export const updateCategory = async (req, res) => { const category = await Category.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true }); if (!category) return res.status(404).json({ success: false, message: 'Category not found' }); return res.status(200).json({ success: true, data: category }); };
export const deleteCategory = async (req, res) => { const category = await Category.findById(req.params.id); if (!category) return res.status(404).json({ success: false, message: 'Category not found' }); const productsCount = await Product.countDocuments({ category: category._id }); if (productsCount) return res.status(409).json({ success: false, message: 'Move or delete products in this category before deleting it' }); await category.deleteOne(); return res.status(200).json({ success: true, message: 'Category deleted' }); };
