import { useEffect, useState } from 'react';
import { Pencil, Plus, Trash2 } from 'lucide-react';
import { toast } from 'react-hot-toast';
import ConfirmModal from '../../components/admin/ConfirmModal';
import { createCategory, deleteCategory, getCategories, updateCategory } from '../../services/categoryService';

const empty = { name: '', slug: '', image: '', description: '', isActive: true };
export default function CategoryManagementPage() {
  const [items, setItems] = useState([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState(null); const [removing, setRemoving] = useState(null); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); getCategories({ includeInactive: true, limit: 100 }).then((result) => setItems(result.data)).catch(() => toast.error('Could not load categories')).finally(() => setLoading(false)); }; useEffect(load, []);
  const submit = async (event) => { event.preventDefault(); try { if (editing) await updateCategory(editing, form); else await createCategory(form); toast.success(`Category ${editing ? 'updated' : 'created'}`); setForm(empty); setEditing(null); load(); } catch (error) { toast.error(error.response?.data?.message || 'Could not save category'); } };
  return <><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Categories</h1><p className="text-sm text-stone-500">Organize the catalogue.</p></div><Plus className="text-brand-700" /></div><form onSubmit={submit} className="mt-6 grid gap-3 rounded-2xl bg-white p-4 shadow-sm ring-1 ring-stone-200 sm:grid-cols-2"><input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value, slug: form.slug || event.target.value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') })} placeholder="Category name" className="rounded-lg border p-2.5" /><input required value={form.slug} onChange={(event) => setForm({ ...form, slug: event.target.value })} placeholder="slug" className="rounded-lg border p-2.5" /><input value={form.image} onChange={(event) => setForm({ ...form, image: event.target.value })} placeholder="Image URL (optional)" className="rounded-lg border p-2.5" /><input value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Description" className="rounded-lg border p-2.5" /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isActive} onChange={(event) => setForm({ ...form, isActive: event.target.checked })} /> Active</label><button className="rounded-lg bg-brand-600 px-4 py-2.5 font-bold text-white">{editing ? 'Save category' : 'Add category'}</button></form><div className="mt-5 overflow-hidden rounded-2xl bg-white ring-1 ring-stone-200"><table className="w-full text-left text-sm"><thead className="bg-stone-50 text-stone-500"><tr><th className="p-4">Name</th><th className="p-4">Slug</th><th className="p-4">Status</th><th className="p-4" /></tr></thead><tbody>{loading ? Array.from({ length: 4 }, (_, index) => <tr key={index}><td colSpan="4" className="p-5"><div className="h-4 animate-pulse rounded bg-stone-200" /></td></tr>) : items.map((item) => <tr key={item._id} className="border-t"><td className="p-4 font-semibold">{item.name}</td><td className="p-4 text-stone-500">{item.slug}</td><td className="p-4">{item.isActive ? 'Active' : 'Hidden'}</td><td className="p-4"><button onClick={() => { setForm(item); setEditing(item._id); }} className="mr-3 text-brand-700"><Pencil size={16} /></button><button onClick={() => setRemoving(item)} className="text-red-600"><Trash2 size={16} /></button></td></tr>)}</tbody></table></div>{removing && <ConfirmModal title="Delete category?" message={`Remove ${removing.name}. Products are not deleted automatically.`} onCancel={() => setRemoving(null)} onConfirm={async () => { try { await deleteCategory(removing._id); toast.success('Category deleted'); setRemoving(null); load(); } catch (error) { toast.error(error.response?.data?.message || 'Could not delete category'); } }} />}</>;
}
