import { useEffect, useState } from 'react';
import { Edit3, Plus, Search, Trash2, X } from 'lucide-react';
import { toast } from 'react-hot-toast';
import ConfirmModal from '../../components/admin/ConfirmModal';
import { getCategories } from '../../services/categoryService';
import { createProduct, deleteProduct, getProducts, updateProduct } from '../../services/productService';

const blank = { title: '', slug: '', description: '', category: '', brand: '', price: '', discountPrice: '', stock: 0, unit: 'pcs', featured: false, isAvailable: true };

function ProductForm({ product, categories, onClose, onSaved }) {
  const [form, setForm] = useState(product ? { ...blank, ...product, category: product.category?._id || product.category } : blank);
  const [files, setFiles] = useState([]); const [previews, setPreviews] = useState([]); const [saving, setSaving] = useState(false);
  useEffect(() => { const urls = files.map((file) => URL.createObjectURL(file)); setPreviews(urls); return () => urls.forEach(URL.revokeObjectURL); }, [files]);
  const updateField = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { const data = new FormData(); Object.entries(form).forEach(([key, value]) => data.append(key, value)); files.forEach((file) => data.append('images', file)); if (product) await updateProduct(product._id, data); else await createProduct(data); toast.success(`Product ${product ? 'updated' : 'created'}`); onSaved(); } catch (error) { toast.error(error.response?.data?.message || 'Could not save product'); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-30 overflow-y-auto bg-stone-950/40 p-4"><form onSubmit={submit} className="mx-auto max-w-3xl rounded-2xl bg-white p-5 shadow-xl"><div className="flex justify-between"><h2 className="text-xl font-bold">{product ? 'Edit product' : 'Add product'}</h2><button type="button" onClick={onClose} aria-label="Close product form"><X /></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2">
    {[['title', 'Product title'], ['slug', 'Slug'], ['brand', 'Brand'], ['price', 'Price'], ['discountPrice', 'Discount price'], ['stock', 'Stock']].map(([key, placeholder]) => <input key={key} required={['title', 'slug', 'price', 'stock'].includes(key)} min={['price', 'discountPrice', 'stock'].includes(key) ? '0' : undefined} step={['price', 'discountPrice'].includes(key) ? '0.01' : undefined} type={['price', 'discountPrice', 'stock'].includes(key) ? 'number' : 'text'} value={form[key]} onChange={(event) => updateField(key, event.target.value)} placeholder={placeholder} className="rounded-lg border border-stone-300 p-2.5" />)}
    <select required value={form.category} onChange={(event) => updateField('category', event.target.value)} className="rounded-lg border border-stone-300 p-2.5"><option value="">Category</option>{categories.map((category) => <option key={category._id} value={category._id}>{category.name}</option>)}</select><select value={form.unit} onChange={(event) => updateField('unit', event.target.value)} className="rounded-lg border border-stone-300 p-2.5">{['kg', 'g', 'litre', 'ml', 'pcs'].map((unit) => <option key={unit}>{unit}</option>)}</select>
    <textarea value={form.description} onChange={(event) => updateField('description', event.target.value)} placeholder="Description" className="min-h-24 rounded-lg border border-stone-300 p-2.5 sm:col-span-2" /><label className="text-sm font-medium sm:col-span-2">Product images (JPEG, PNG, or WebP; max 5 MB each)<input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={(event) => setFiles(Array.from(event.target.files || []))} className="mt-1 block w-full text-sm" /></label>
    {(previews.length > 0 || product?.images?.length > 0) && <div className="flex flex-wrap gap-2 sm:col-span-2">{product?.images?.map((image) => <img key={image.url} src={image.url} alt="Current product" className="h-16 w-16 rounded-lg object-cover" />)}{previews.map((url) => <img key={url} src={url} alt="Selected upload" className="h-16 w-16 rounded-lg object-cover" />)}</div>}
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.featured} onChange={(event) => updateField('featured', event.target.checked)} /> Featured product</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isAvailable} onChange={(event) => updateField('isAvailable', event.target.checked)} /> Available for sale</label>
  </div><button disabled={saving} className="mt-5 rounded-lg bg-brand-600 px-5 py-2.5 font-bold text-white disabled:opacity-60">{saving ? 'Saving…' : 'Save product'}</button></form></div>;
}

export default function ProductManagementPage() {
  const [items, setItems] = useState([]); const [categories, setCategories] = useState([]); const [search, setSearch] = useState(''); const [category, setCategory] = useState(''); const [minPrice, setMinPrice] = useState(''); const [maxPrice, setMaxPrice] = useState(''); const [sort, setSort] = useState('newest'); const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [loading, setLoading] = useState(true); const [editing, setEditing] = useState(undefined); const [removing, setRemoving] = useState(null);
  const load = () => { setLoading(true); getProducts({ includeUnavailable: true, search: search || undefined, category: category || undefined, minPrice: minPrice || undefined, maxPrice: maxPrice || undefined, page, limit: 10, sort }).then((result) => { setItems(result.data); setPages(result.pagination.pages || 1); }).catch(() => toast.error('Could not load products')).finally(() => setLoading(false)); };
  useEffect(load, [page, category, minPrice, maxPrice, search, sort]); useEffect(() => { getCategories({ includeInactive: true, limit: 100 }).then((result) => setCategories(result.data)).catch(() => toast.error('Could not load categories')); }, []);
  const resetPage = (setter) => (event) => { setter(event.target.value); setPage(1); };
  return <><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Products</h1><p className="text-sm text-stone-500">Manage grocery inventory.</p></div><button onClick={() => setEditing(null)} className="inline-flex items-center gap-2 rounded-lg bg-brand-600 px-4 py-2.5 font-bold text-white"><Plus size={18} /> Add product</button></div>
    <div className="mt-5 grid gap-3 rounded-2xl bg-white p-4 ring-1 ring-stone-200 sm:grid-cols-2 lg:grid-cols-5"><label className="relative sm:col-span-2"><Search size={17} className="absolute left-3 top-3 text-stone-400" /><input value={search} onChange={resetPage(setSearch)} placeholder="Search products" className="w-full rounded-lg border border-stone-300 bg-white py-2.5 pl-9 pr-3" /></label><select value={category} onChange={resetPage(setCategory)} className="rounded-lg border border-stone-300 bg-white p-2.5"><option value="">All categories</option>{categories.map((item) => <option key={item._id} value={item.slug}>{item.name}</option>)}</select><select value={sort} onChange={resetPage(setSort)} className="rounded-lg border border-stone-300 bg-white p-2.5"><option value="newest">Newest</option><option value="price_asc">Price: low to high</option><option value="price_desc">Price: high to low</option><option value="rating">Highest rated</option></select><div className="flex gap-2"><input value={minPrice} onChange={resetPage(setMinPrice)} min="0" type="number" placeholder="Min price" className="min-w-0 w-full rounded-lg border border-stone-300 p-2.5" /><input value={maxPrice} onChange={resetPage(setMaxPrice)} min="0" type="number" placeholder="Max price" className="min-w-0 w-full rounded-lg border border-stone-300 p-2.5" /></div></div>
    <div className="mt-5 overflow-x-auto rounded-2xl bg-white ring-1 ring-stone-200"><table className="w-full min-w-150 text-left text-sm"><thead className="bg-stone-50 text-stone-500"><tr><th className="p-4">Product</th><th className="p-4">Category</th><th className="p-4">Price</th><th className="p-4">Stock</th><th className="p-4" /></tr></thead><tbody>{loading ? Array.from({ length: 6 }, (_, index) => <tr key={index}><td colSpan="5" className="p-5"><div className="h-5 animate-pulse rounded bg-stone-200" /></td></tr>) : items.map((item) => <tr key={item._id} className="border-t"><td className="p-4"><div className="flex items-center gap-3"><img src={item.images?.[0]?.url || 'https://placehold.co/80'} alt="" className="h-9 w-9 rounded object-cover" /><span className="font-semibold">{item.title}</span></div></td><td className="p-4">{item.category?.name}</td><td className="p-4">₹{item.discountPrice ?? item.price}</td><td className="p-4">{item.stock} {item.unit}</td><td className="p-4"><button onClick={() => setEditing(item)} className="mr-3 text-brand-700" aria-label={`Edit ${item.title}`}><Edit3 size={16} /></button><button onClick={() => setRemoving(item)} className="text-red-600" aria-label={`Delete ${item.title}`}><Trash2 size={16} /></button></td></tr>)}</tbody></table></div>
    <div className="mt-4 flex justify-end gap-2"><button disabled={page === 1} onClick={() => setPage((current) => current - 1)} className="rounded border px-3 py-1.5 disabled:opacity-40">Previous</button><span className="px-2 py-1.5 text-sm">{page} / {pages}</span><button disabled={page === pages} onClick={() => setPage((current) => current + 1)} className="rounded border px-3 py-1.5 disabled:opacity-40">Next</button></div>
    {editing !== undefined && <ProductForm product={editing} categories={categories} onClose={() => setEditing(undefined)} onSaved={() => { setEditing(undefined); load(); }} />}{removing && <ConfirmModal title="Delete product?" message={`This permanently removes ${removing.title} and its Cloudinary images.`} onCancel={() => setRemoving(null)} onConfirm={async () => { try { await deleteProduct(removing._id); toast.success('Product deleted'); setRemoving(null); load(); } catch (error) { toast.error(error.response?.data?.message || 'Could not delete product'); } }} />}</>;
}
